version: "3.7"

services:
  app:
    build: ./docker/php
    volumes:
      - ./web:/work/web
    networks:
      - default
      - famous_quote

  web:
    image: nginx
    ports:
      - 12000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/work/web
    depends_on:
      - app
    networks:
      - default
      - famous_quote

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./db-store:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=famous_quote
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    networks:
      - default
      - famous_quote

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 12345:80
    networks:
      - default
      - famous_quote

networks:
  famous_quote:
    external: true