version: "3.8"

services:
  app:
    build: ./docker/php
    volumes:
      - ./web:/work/web

  web:
    image: nginx
    ports:
      - ${IP}:80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/work/web
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./db-store:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD={DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    links:
      - mysql
    ports:
      - ${IP}:1234:80
